import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/booking_model.dart';
import '../models/job_model.dart';
import '../models/user_model.dart';

class MockDataService {
  static List<JobModel> allJobs = [
    JobModel(
      id: 'j001',
      title: 'Coffee Shop Assistant',
      category: 'Cafe',
      wagePerHour: 120,
      lat: 12.9716,
      lng: 77.5946,
      address: 'Brew Brothers Cafe, Indiranagar',
      city: 'Bengaluru',
      duration: '5 hrs',
      shiftTime: '7:00 AM – 12:00 PM',
      date: 'Today',
      description: 'Help with morning coffee rush – taking orders, serving, cleaning tables. Friendly atmosphere!',
      requirements: ['No experience needed', 'Punctual', 'Polite with customers'],
      employerId: 'e001',
      employerName: 'Arjun Mehta',
      employerRating: 4.7,
      employerVerified: true,
      workersNeeded: 2,
      workersBooked: 0,
      status: 'open',
    ),
    JobModel(
      id: 'j002',
      title: 'Delivery Partner',
      category: 'Delivery',
      wagePerHour: 150,
      lat: 12.9352,
      lng: 77.6245,
      address: 'Koramangala Hub, Bengaluru',
      city: 'Bengaluru',
      duration: '6 hrs',
      shiftTime: '5:00 PM – 11:00 PM',
      date: 'Today',
      description: 'Evening food deliveries in Koramangala. Bike required. GPS tracking provided via app.',
      requirements: ['Own bike + license', '18+ years', 'Smartphone'],
      employerId: 'e002',
      employerName: 'Priya Foods Pvt Ltd',
      employerRating: 4.5,
      employerVerified: true,
      workersNeeded: 5,
      workersBooked: 2,
      status: 'open',
    ),
    JobModel(
      id: 'j003',
      title: 'IT Event Support',
      category: 'IT Support',
      wagePerHour: 250,
      lat: 12.9544,
      lng: 77.4980,
      address: 'Electronic City Phase 2',
      city: 'Bengaluru',
      duration: '8 hrs',
      shiftTime: '9:00 AM – 5:00 PM',
      date: 'Tomorrow',
      description: 'On-site tech support for corporate conference. Setup projectors, handle AV equipment.',
      requirements: ['Basic computer knowledge', 'Smart appearance', 'Class 12+'],
      employerId: 'e003',
      employerName: 'TechMeet Solutions',
      employerRating: 4.9,
      employerVerified: true,
      workersNeeded: 3,
      workersBooked: 1,
      status: 'open',
    ),
    JobModel(
      id: 'j004',
      title: 'Retail Store Helper',
      category: 'Retail',
      wagePerHour: 100,
      lat: 12.9953,
      lng: 77.6960,
      address: 'Phoenix Marketcity, Whitefield',
      city: 'Bengaluru',
      duration: '4 hrs',
      shiftTime: '3:00 PM – 7:00 PM',
      date: 'Today',
      description: 'Weekend sale helper – restocking shelves, assisting customers, billing support.',
      requirements: ['Energetic', 'Basic English', 'Comfortable standing'],
      employerId: 'e004',
      employerName: 'FashionZone India',
      employerRating: 4.3,
      employerVerified: true,
      workersNeeded: 4,
      workersBooked: 2,
      status: 'open',
    ),
    JobModel(
      id: 'j005',
      title: 'Warehouse Loader',
      category: 'Warehouse',
      wagePerHour: 130,
      lat: 13.0358,
      lng: 77.5970,
      address: 'Yelahanka Industrial Area',
      city: 'Bengaluru',
      duration: '6 hrs',
      shiftTime: '6:00 AM – 12:00 PM',
      date: 'Today',
      description: 'Loading/unloading goods at FMCG warehouse. Physical work – must be fit.',
      requirements: ['Physical fitness', '18+ years', 'Any education'],
      employerId: 'e005',
      employerName: 'FastLog Warehousing',
      employerRating: 4.1,
      employerVerified: false,
      workersNeeded: 8,
      workersBooked: 3,
      status: 'open',
    ),
    JobModel(
      id: 'j006',
      title: 'Wedding Event Staff',
      category: 'Event',
      wagePerHour: 200,
      lat: 12.9141,
      lng: 77.6377,
      address: 'The Grand Banquet, HSR Layout',
      city: 'Bengaluru',
      duration: '10 hrs',
      shiftTime: '12:00 PM – 10:00 PM',
      date: '18 Mar',
      description: 'Help manage wedding reception – welcome guests, serve food, manage decorations.',
      requirements: ['Formal attire (provided)', 'Telugu/Kannada preferred', 'Responsible'],
      employerId: 'e006',
      employerName: 'Celebrations Events Co.',
      employerRating: 4.8,
      employerVerified: true,
      workersNeeded: 10,
      workersBooked: 4,
      status: 'open',
    ),
    JobModel(
      id: 'j007',
      title: 'Maths Tutor – Class 10',
      category: 'Tutoring',
      wagePerHour: 300,
      lat: 12.9259,
      lng: 77.6762,
      address: 'Bellandur, Bengaluru',
      city: 'Bengaluru',
      duration: '2 hrs',
      shiftTime: '4:00 PM – 6:00 PM',
      date: 'Today',
      description: 'Teach Class 10 CBSE Maths to two students. Algebra + Geometry focus.',
      requirements: ['Engineering/BSc student', 'Strong in Maths', 'Patient teacher'],
      employerId: 'e007',
      employerName: 'Ramesh Nair (Parent)',
      employerRating: 5.0,
      employerVerified: true,
      workersNeeded: 1,
      workersBooked: 0,
      status: 'open',
    ),
    JobModel(
      id: 'j008',
      title: 'Security Guard – Night',
      category: 'Security',
      wagePerHour: 110,
      lat: 12.9781,
      lng: 77.5908,
      address: 'MG Road Commercial Complex',
      city: 'Bengaluru',
      duration: '8 hrs',
      shiftTime: '10:00 PM – 6:00 AM',
      date: 'Today',
      description: 'Night security for commercial building. Round duty, CCTV monitoring.',
      requirements: ['Ex-military preferred', '25+ years', 'Physical fitness certificate'],
      employerId: 'e008',
      employerName: 'SecureKeep Corp',
      employerRating: 3.9,
      employerVerified: true,
      workersNeeded: 2,
      workersBooked: 1,
      status: 'open',
    ),
    JobModel(
      id: 'j009',
      title: 'Office Cleaning Staff',
      category: 'Cleaning',
      wagePerHour: 90,
      lat: 12.9698,
      lng: 77.7499,
      address: 'Marathahalli Tech Park',
      city: 'Bengaluru',
      duration: '3 hrs',
      shiftTime: '7:00 AM – 10:00 AM',
      date: 'Tomorrow',
      description: 'Morning office cleaning – sweep, mop, sanitize. Equipment provided.',
      requirements: ['Any education', 'Responsible', 'Punctual'],
      employerId: 'e009',
      employerName: 'CleanPro Services',
      employerRating: 4.0,
      employerVerified: true,
      workersNeeded: 3,
      workersBooked: 0,
      status: 'open',
    ),
    JobModel(
      id: 'j010',
      title: 'Cloud Kitchen Cook Helper',
      category: 'Cooking',
      wagePerHour: 140,
      lat: 12.9483,
      lng: 77.5846,
      address: 'Jayanagar Cloud Kitchen',
      city: 'Bengaluru',
      duration: '5 hrs',
      shiftTime: '11:00 AM – 4:00 PM',
      date: 'Today',
      description: 'Assist head chef – chopping, cleaning, packing orders. Lunch provided!',
      requirements: ['Basic cooking experience', 'Clean habits', 'Team player'],
      employerId: 'e010',
      employerName: 'TastyBites Kitchen',
      employerRating: 4.6,
      employerVerified: true,
      workersNeeded: 2,
      workersBooked: 1,
      status: 'open',
    ),
    JobModel(
      id: 'j011',
      title: 'Data Entry Operator',
      category: 'IT Support',
      wagePerHour: 180,
      lat: 12.9631,
      lng: 77.5933,
      address: 'Sadashivanagar, Bengaluru',
      city: 'Bengaluru',
      duration: '6 hrs',
      shiftTime: '10:00 AM – 4:00 PM',
      date: 'Tomorrow',
      description: 'Enter scanned documents into Excel. Basic computer skills needed. AC office.',
      requirements: ['Typing speed 30+ WPM', 'MS Excel basics', 'Any graduate'],
      employerId: 'e011',
      employerName: 'DataFirst Pvt Ltd',
      employerRating: 4.4,
      employerVerified: true,
      workersNeeded: 4,
      workersBooked: 2,
      status: 'open',
    ),
    JobModel(
      id: 'j012',
      title: 'Supermarket Cashier',
      category: 'Retail',
      wagePerHour: 115,
      lat: 12.9550,
      lng: 77.7011,
      address: 'Big Bazaar, Varthur Road',
      city: 'Bengaluru',
      duration: '8 hrs',
      shiftTime: '9:00 AM – 5:00 PM',
      date: '18 Mar',
      description: 'Weekend cashier for busy supermarket. Billing software training provided.',
      requirements: ['10th pass', 'Basic maths', 'Friendly attitude'],
      employerId: 'e012',
      employerName: 'Big Bazaar (Future Group)',
      employerRating: 4.2,
      employerVerified: true,
      workersNeeded: 6,
      workersBooked: 3,
      status: 'open',
    ),
  ];

  static final List<UserModel> allWorkers = [
    const UserModel(
      id: 'w001',
      name: 'Rahul Sharma',
      phone: '+91 98765 43210',
      role: 'worker',
      trustScore: 91,
      rating: 4.8,
      lat: 12.9716,
      lng: 77.5946,
      city: 'Bengaluru',
      skills: ['Delivery', 'Retail', 'Warehouse'],
      walletBalance: 3450,
      jobsCompleted: 47,
      isVerified: true,
    ),
    const UserModel(
      id: 'w002',
      name: 'Priya Nair',
      phone: '+91 87654 32109',
      role: 'worker',
      trustScore: 85,
      rating: 4.6,
      lat: 12.9352,
      lng: 77.6245,
      city: 'Bengaluru',
      skills: ['Tutoring', 'IT Support', 'Cafe'],
      walletBalance: 6720,
      jobsCompleted: 33,
      isVerified: true,
    ),
    const UserModel(
      id: 'w003',
      name: 'Aditya Kumar',
      phone: '+91 76543 21098',
      role: 'worker',
      trustScore: 72,
      rating: 4.2,
      lat: 12.9544,
      lng: 77.4980,
      city: 'Bengaluru',
      skills: ['Warehouse', 'Delivery', 'Security'],
      walletBalance: 1890,
      jobsCompleted: 18,
      isVerified: true,
    ),
    const UserModel(
      id: 'w004',
      name: 'Sneha Reddy',
      phone: '+91 65432 10987',
      role: 'worker',
      trustScore: 95,
      rating: 4.9,
      lat: 12.9953,
      lng: 77.6960,
      city: 'Bengaluru',
      skills: ['Cafe', 'Event', 'Retail'],
      walletBalance: 11200,
      jobsCompleted: 82,
      isVerified: true,
    ),
    const UserModel(
      id: 'w005',
      name: 'Mohammed Irfan',
      phone: '+91 54321 09876',
      role: 'worker',
      trustScore: 68,
      rating: 4.0,
      lat: 13.0358,
      lng: 77.5970,
      city: 'Bengaluru',
      skills: ['Delivery', 'Cooking', 'Cleaning'],
      walletBalance: 2340,
      jobsCompleted: 12,
      isVerified: false,
    ),
  ];

  static final List<UserModel> allEmployers = [
    const UserModel(
      id: 'e001',
      name: 'Arjun Mehta',
      phone: '+91 99887 76655',
      role: 'employer',
      trustScore: 95,
      rating: 4.7,
      lat: 12.9716,
      lng: 77.5946,
      city: 'Bengaluru',
      skills: [],
      walletBalance: 45000,
      jobsCompleted: 127,
      isVerified: true,
    ),
    const UserModel(
      id: 'e002',
      name: 'Priya Foods Pvt Ltd',
      phone: '+91 88776 65544',
      role: 'employer',
      trustScore: 88,
      rating: 4.5,
      lat: 12.9352,
      lng: 77.6245,
      city: 'Bengaluru',
      skills: [],
      walletBalance: 230000,
      jobsCompleted: 342,
      isVerified: true,
    ),
  ];

  // Mock booking history for the logged-in worker
  static final List<BookingModel> myBookings = [
    BookingModel(
      id: 'b001',
      jobId: 'j001',
      workerId: 'w001',
      jobTitle: 'Coffee Shop Assistant',
      employerName: 'Brew Brothers Cafe',
      shiftTime: '7:00 AM – 12:00 PM',
      date: 'Today',
      address: 'Indiranagar, Bengaluru',
      wagePerHour: 120,
      duration: '5 hrs',
      status: 'confirmed',
      bookedAt: DateTime(2026, 3, 17, 10, 30),
    ),
    BookingModel(
      id: 'b002',
      jobId: 'j003',
      workerId: 'w001',
      jobTitle: 'IT Event Support',
      employerName: 'TechMeet Solutions',
      shiftTime: '9:00 AM – 5:00 PM',
      date: 'Tomorrow',
      address: 'Electronic City, Bengaluru',
      wagePerHour: 250,
      duration: '8 hrs',
      status: 'confirmed',
      bookedAt: DateTime(2026, 3, 17, 9, 15),
    ),
    BookingModel(
      id: 'b003',
      jobId: 'j007',
      workerId: 'w001',
      jobTitle: 'Maths Tutor – Class 10',
      employerName: 'Ramesh Nair (Parent)',
      shiftTime: '4:00 PM – 6:00 PM',
      date: '15 Mar',
      address: 'Bellandur, Bengaluru',
      wagePerHour: 300,
      duration: '2 hrs',
      status: 'completed',
      bookedAt: DateTime(2026, 3, 14, 16, 0),
      earnedAmount: 600,
    ),
    BookingModel(
      id: 'b004',
      jobId: 'j002',
      workerId: 'w001',
      jobTitle: 'Delivery Partner',
      employerName: 'Priya Foods Pvt Ltd',
      shiftTime: '5:00 PM – 11:00 PM',
      date: '14 Mar',
      address: 'Koramangala, Bengaluru',
      wagePerHour: 150,
      duration: '6 hrs',
      status: 'completed',
      bookedAt: DateTime(2026, 3, 13, 15, 0),
      earnedAmount: 900,
    ),
    BookingModel(
      id: 'b005',
      jobId: 'j010',
      workerId: 'w001',
      jobTitle: 'Cloud Kitchen Cook Helper',
      employerName: 'TastyBites Kitchen',
      shiftTime: '11:00 AM – 4:00 PM',
      date: '12 Mar',
      address: 'Jayanagar, Bengaluru',
      wagePerHour: 140,
      duration: '5 hrs',
      status: 'completed',
      bookedAt: DateTime(2026, 3, 11, 18, 0),
      earnedAmount: 700,
    ),
  ];

  // Weekly earnings data (last 7 days)
  static const List<double> weeklyEarnings = [0, 900, 0, 700, 0, 600, 0];
  static const List<String> weekDays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final String? jobsJson = prefs.getString('mock_jobs');
    if (jobsJson != null) {
      final List<dynamic> decoded = jsonDecode(jobsJson);
      allJobs = decoded.map((e) => JobModel.fromJson(e)).toList();
    }
  }

  static Future<void> saveJobs() async {
    final prefs = await SharedPreferences.getInstance();
    final String encoded = jsonEncode(allJobs.map((e) => e.toJson()).toList());
    await prefs.setString('mock_jobs', encoded);
  }
}

